Next methods
GorgiMitev/enumerables_microverse pull request #1
Opened 2021-04-02 08:41 UTC by Solenka1

Creating the required methods
* Adding each method 
* Testing and debugging each method

2021-04-02 18:21 UTC, DeliceLydia requested changes
# Status: Change Requested

Good job so far @Solenka1 I can see you worked hard to reach this far but there is always room for improvement that is why you need to make some changes  in your project so that it can be approved

## To highlight ![image](https://user-images.githubusercontent.com/44745855/113442280-0b8a9e00-93f0-11eb-9147-0a88b58d0fbc.png)

- my_each is working when the block is given
- my_each_with index is working when the block is given
- my_none is working when a block is given
- my_all method is working when a block is given
- my_any is working when a block is given
- my inject is finding the longest word and when a block is given without an initial value it is combining all elements of enum by applying a binary operation, specified by a block
- remember to remove all commented code in your project to make it neat

## To improve ![image](https://user-images.githubusercontent.com/44745855/113442419-51476680-93f0-11eb-8ecf-df58a4d2ee87.png)

- my_each method If no block is given, an enumerator is returned instead.
- my_each_with index method If no block is given, an enumerator is returned instead.

### My_select
- Returns an array containing all elements of enum for which the given block returns a true value but yours return nothing
-  If no block is given, an Enumerator is returned instead.

### My_all
- when no block or argument is given returns false when one of the collection members is false or nil
- when a class is passed as an argument returns true if all of the collection is a member of such class
- when a Regex is passed as an argument returns true if all of the collection matches the Regex
- when a pattern other than Regex or a Class is given returns true if all of the collection matches the pattern

### My_any
- when no block or argument is given returns true if at least one of the collection is not false or nil
- when a class is passed as an argument returns true if at least one of the collection is a member of such class
- when a Regex is passed as an argument returns false if none of the collection matches the Regex
- when a pattern other than Regex or a Class is given returns false if none of the collection matches the pattern

### My_none
- when no block or argument is given returns false only if one of the collection members is true
- when a class is passed as an argument returns true if none of the collection is a member of such class
- when a Regex is passed as an argument returns false if any of the collection matches the Regex
- when a pattern other than Regex or a Class is given returns true only if none of the collection matches the pattern

### My_count

- Counts the number of elements yielding a true value if a block is given
- Does not mutate the original array

### My_map

- Returns a new array with the results of running a given block once for every element in enum
- Returns an Enumerator if no block is given
- Accepts a proc as an argument and returns a new array with the results of running the proc once for every element in enum

### My_inject

- when a block is given without an initial value combines all elements of enum by applying a binary operation, specified by a block
- when a symbol is specified without an initial value combines each element of the collection by applying the symbol as a named method

## N.B
KIndly follow this guide [here](https://ruby-doc.org/core-2.6.1/Enumerable.html) it can help and don't give up

All the best,

Lydia Ingabire

2021-04-03 14:21 UTC, e71az requested changes
# Status:  Changes Required ♻️

Hello @Solenka1,

Remember to create more descriptive commit messages, for example, your "correcting errors" and "fixing errors" are not descriptive enough. Take that into account for all your future commit messages as a developer.

I noticed something, some of your variables inside the functions that you are trying to use were never created thus making most of the functions that use them fail. This makes me think that you are not testing your code before submitting another code review (I hope to be wrong).

In my opinion, this is one of the most important projects in microverse in which you will have to test your functions a lot because you need to check all the use cases and correct all the failing ones until your function behaves exactly the same as the original enumerable ones from Ruby. Please take this into account for your next submission. Don't take me wrong, this is no easy project and you are doing great on it so far, keep it up! :)

In this project, you have to refer a lot to the link pointed out by the previous TSE [Enumerables](https://ruby-doc.org/core-2.6.1/Enumerable.html) and grab all of the test examples that they are using to test your own functions and assure that you get back exactly the same output. If there are not enough code examples (like only 1 or 2) google the function that you are trying to replicate and grab more samples until it covers all of the edge cases.

Please correct the issues that I pointed you plus the ones that the previous TSE told you about and send another code review request, good luck!

2021-04-03 14:21 UTC, eliasecasta commented on enumerables.rb
> +      my_each { |i| new_arr << yield(i) }
- [x] new_arr doesn't exist.

2021-04-03 14:21 UTC, eliasecasta commented on enumerables.rb
> +  def my_count
- [x]  Should accept arguments, try something like this: def my_count(*args)

2021-04-03 14:21 UTC, eliasecasta commented on enumerables.rb
> +  end
- [x] These two functions are giving issues to the other functions that use them, please fix your while i < length logic. In our tests we are using range to create some values and it is giving problems.

What I did and what I advise you to do is to convert your self to_a first and so you can work with it as an array. Another recommendation is to use array.times to yield the elements needed instead of using this while loop with a counter.

2021-04-03 14:21 UTC, e71az commented on enumerables.rb
> +      my_each { |i| results << proc.call(yield(i)) }
- [ ] You declared result but instead used results.

2021-04-06 10:52 UTC, Berabjesus approved these changes
# **Status: PROJECT APPROVED** 

#### Excellent job on this project @Solenka1 . :fireworks: Keep it up.  :champagne: :champagne: **All the required tasks have been fulfilled in this project. I will go ahead and mark this as complete. 👍** 

I wish you all the very best in your next tasks:1st_place_medal:
#### **If you have any questions, let me know by leaving a comment here and mentioning me. I will be happy to help** 
**HAPPY CODING :computer:[Bereket Beshane](https://bereketababu.me)** | [LinkedIn](https://linkedin.com/in/bereketbeshane) | [GitHub](https://github.com/Berabjesus)

2021-04-06 11:18 UTC, merged